spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zhelezov2017/ServiceConfigProperties.git/
          search-paths:
            - "EmailServiceConfigProperties/{application}/{profile}"